### ISSUE TITLE
cmake . 出现BUG，求教

### ISSUE THREAD

**Issue by qichaotang** [tobegit3hub/hplearn#1]
![image](https://user-images.githubusercontent.com/12878507/30001434-b981c006-90c0-11e7-9b51-07fe258c3af2.png)
MAC运行 cmake 出现这种问题，glog源码编译安装

**Comment by qichaotang** [comment]
![image](https://user-images.githubusercontent.com/12878507/30001443-04be873e-90c1-11e7-82c6-367f067a4dce.png)

**Comment by tobegit3hub** [comment]
Sorry for the issue. `glog` and `gflags` are not used yet but now we need to install from source to run `hplearn`.

This is not required and I will remove the dependencies soon so that you can build `hplearn` easily.

Thanks for your feedback.

**Comment by tobegit3hub** [comment]
Please clone the latest code and have a test @qichaotang 😃

**Comment by qichaotang** [comment]
可以运行了，不过 glog and gflags 这两个打log的包，没装上就有些奇怪了，毕竟debug时候需要尽可能的打log，

**Comment by qichaotang** [comment]
话说LZ，你的这个怎么 git push ？好像没有啥权限，我发现了你的 benchmark 文件夹里面的BUG，需要把 src 都改为 hplearn ，路径出现了错误，想跟你修复下的，but，git push 不了，有点遗憾，哈哈

**Comment by tobegit3hub** [comment]
Of course you are not allowed to push to this repository directory.

It would be great to send pull-request to fix that and join the open-source community. You should fork the project firstly and search "Github pull request" for more help.

**Comment by qichaotang** [comment]
ok,thanks

**Comment by qichaotang** [comment]
I try it today
